### ISSUE TITLE
How to behave if the project is for OSX and iOS

### ISSUE THREAD

**Issue by adriano-di-giovanni** [danomatika/ofxMidi#35]
May I leave all folders in addons/ofxMidi group? Maybe it should be stated in README.

Thanks for ofxMidi :)

**Comment by danomatika** [comment]
It doesn't explicitly _have_ to be in the add ons group since groups are only organization helpers. Xcode goes through and finds all the listed files no matter where they are in the layout. I do agree, however, that it's best to stick with the default layout and put them in `add ons`. I always do this.
