### ISSUE TITLE
Syncing multiple synths

### ISSUE THREAD

**Issue by microcosm** [danomatika/ofxMidi#37]
I'm trying to sync two LFOs on different synths using MIDI [Real-Time messages](http://www.recordingblogs.com/sa/tabid/88/Default.aspx?topic=MIDI+system+realtime+messages). Is this supported by ofxMidi?

I have tried by sending ```ofxMidiOut.sendMidiByte(MIDI_START)``` and then ```ofxMidiOut.sendMidiByte(MIDI_TIME_CLOCK)``` at timed intervals. But the synths aren't respecting it.

I think it might be one of two reasons:

1. According to this [real-time messages reference](http://www.recordingblogs.com/sa/tabid/88/Default.aspx?topic=MIDI+system+realtime+messages), real-time messages are general and not sent to any port. But deep inside the ```RtMidi``` class ```MidiOutCore.sendMessage``` is calling ```CoreMIDI/MidiServices.MIDISend```, which takes a ```MIDIPortRef``` port argument. I can't find a port-agnostic equivalent of ```MIDISend``` in that file. So maybe it's not possible?

2. It says on this [MIDI Clock message reference](http://www.recordingblogs.com/sa/tabid/88/Default.aspx?topic=MIDI+Clock+message) that the length of a quarter note also depends on other MIDI messages, such as the [MIDI Set Tempo meta message](http://www.recordingblogs.com/sa/tabid/88/Default.aspx?topic=MIDI+Set+Tempo+meta+message). However it also [says that](http://www.recordingblogs.com/sa/tabid/88/Default.aspx?topic=MIDI+meta+messages) meta messages are "never sent over MIDI ports, but exist in MIDI files". So I'm not sure if/how to send meta messages with ofxMidi.

I'm not sure how to proceed. Are others here able to sync multiple synths from their openFrameworks apps?

**Comment by danomatika** [comment]
I can answer question 1, but only speculate on question 2. Tempo itself doesn't matter since, conceptual, different sequencers could be set to different tempos, even though they receive the same clock signal which simply keeps their ticks in line.

>Are others here able to sync multiple synths from their openFrameworks apps?

The short answer is no, most people aren't using MIDI clock in their OF apps.

>I'm not sure how to proceed.

The long answer is yes, this is possible, but probably not with RtMidi, at least in a cross platform way since it's missing a realtime timer to generate the correct clock timing. See the forum post starting here: http://forum.openframeworks.cc/t/ofxmidi-updates/2435/89?u=danomatika

The way forward is to transition the desktop backend to use PortMidi which has both delta time sending and an accurate timer. There is a proof of concept port midi branch with the sender using port midi. I haven't taken things any further because, either way, both MIDI libs need to be updated to support the features ofxMidi currently and  I've just been busy with other things. Here's the issue:

1. RTMidi doesn't support delta timestamp sending *and* doesn't have a cross platform timer for scheduling clock messages accurately

2. PortMidi doesn't support creating named virtual midi ports on OS X & Linux which RtMidi does.

My long term goal is to pull the virtual port creation code out of RTMidi, add it it PortMidi, and submit the changes upstream for which there is interest.

**Comment by microcosm** [comment]
Thanks for the detailed reply. That's a fair amount of work, involving changes to two repos, so I will consider it off the cards for now and close the issue.

I was thinking that a cheap alternative would be to set the values of the LFOs in hertz, and to use the OF app to calculate an appropriate hertz value based on the BPM in use in the app. In theory at least that should have the same effect.

**Comment by danomatika** [comment]
Yeah sorry. No easy answer. It's on my list but there hasn't been a large need for full midi compliance.

If you are only using MIDI for inter app communication, I'd suggest using OSC anyway.

**Comment by microcosm** [comment]
I'm sending MIDI to Audio Units:
https://github.com/admsyn/ofxAudioUnit
https://github.com/microcosm/ofxAudioUnitManager

On Fri, Jul 3, 2015 at 3:31 PM, Dan Wilcox <notifications@github.com> wrote:

> Yeah sorry. No easy answer. It's on my list but there hasn't been a large
> need for full midi compliance.
>
> If you are only using MIDI for inter app communication, I'd suggest using
> OSC anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danomatika/ofxMidi/issues/37#issuecomment-118411488>.
>



-- 
*Andrew McWilliams*

<http://jahya.net/>

jahya.net
hardwarehacklab.io
artahack.io
