### ISSUE TITLE
newMidiMessage not called.

### ISSUE THREAD

**Issue by flyingrub** [danomatika/ofxMidi#40]
https://gist.github.com/flyingrub/012441d8a4693aff15f6 > Log and files.

It does now compile (i recompiled and resinstalled all depencies). It doesn't complain that the device isn't set. But it won't trigger newMidiMessage. So i'm wondering if the class should herit from ofBaseApp obligatory ?

**Comment by danomatika** [comment]
Those "RtApiAudio" errors refer to the RT Audio library, **not** the Rt Midi library used by ofxMidi on desktop OSs.

**Comment by danomatika** [comment]
No, the midi listener doesn't need to inherit from an ofBaseApp. You're problem is probably related to running the setup in the constructor. Don't do that. Make a setup function and explicitly call from your ofApp setup. This is because you can't guarantee when the constructor gets called unless your creating things using pointers and things might be getting inited too early on.

**Comment by danomatika** [comment]
This issue is probably relates to creating static ofxMidi objects: https://github.com/danomatika/ofxMidi#using-static-ofxmidi-objects-on-linux-causes-seg-faults

**Comment by flyingrub** [comment]
that did the tricks, thanks :)
